kind: Deployment
apiVersion: apps/v1
metadata:
  name: rem-device
  namespace: default
  labels:
    app: rem-device
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rem-device
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rem-device
    spec:
      containers:
        - name: device
          image: ghcr.io/6-abs-dev/device:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: rem-device
  namespace: default
  labels:
    app: rem-device
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30886
  selector:
    app: rem-device
  clusterIP: 10.96.22.74
  clusterIPs:
    - 10.96.22.74
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
